
questionText = 'How underserved is the geographic area where the project will be built?'
useUrl = 'Use U. of Wisconsin Area Deprivation Index (state deciles)'
url = 'https://www.neighborhoodatlas.medicine.wisc.edu/mapping'
answers = [
  { text = '1', points = 1.0 },
  { text = '2', points = 2.0 },
  { text = '3', points = 3.0 },
  { text = '4', points = 4.0 },
  { text = '5', points = 5.0 },
  { text = '6', points = 6.0 },
  { text = '7', points = 7.0 },
  { text = '8', points = 8.0 },
  { text = '9', points = 9.0 },
  { text = '10', points = 10.0 },
]
answerLeadingHeader = 'ADI'
domain = 'Equity'
autoFillEnabled = false
buttonText = 'ADI'
instructionsMarkdown = '''
* Click the link provided for the U. of Wisconsin Area Deprivation Index (ADI), [available here.](https://www.neighborhoodatlas.medicine.wisc.edu/mapping)
* Select Nevada
* Ensure “State-Only Deciles” is selected (this is the default)
* Enter the test address located within the project area.
* Select “Search”
* A State Decile Information box will appear. Use this for the ADI value AND the point value.
  * If the project area straddles multiple state decile values, average them.
  * Round decimal of .5 or more up to the next whole number and decimals under .5 down.
* Place the value, between 1 and 10 in the “Pts” column'''
videoId = '1LJynIeiBG8sgR84NZj1VV8XQ_DLKc2_l'
hint = ''
